config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :criteres
  resources :style_interactions
  resources :plateforms
  resources :domaines
  resources :questions
  resources :auteurs
  resources :catagories

end

app/controllers/plateforms_controller.rb
class PlateformsController < ApplicationController
  before_action :set_plateform, only: [:show, :edit, :update, :destroy]

  # GET /plateforms
  # GET /plateforms.json
  def index
    @plateforms = Plateform.all
  end

  # GET /plateforms/1
  # GET /plateforms/1.json
  def show
  end

  # GET /plateforms/new
  def new
    @plateform = Plateform.new
  end

  # GET /plateforms/1/edit
  def edit
  end

  # POST /plateforms
  # POST /plateforms.json
  def create
    @plateform = Plateform.new(plateform_params)

    respond_to do |format|
      if @plateform.save
        format.html { redirect_to @plateform, notice: 'Plateform was successfully created.' }
        format.json { render :show, status: :created, location: @plateform }
      else
        format.html { render :new }
        format.json { render json: @plateform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plateforms/1
  # PATCH/PUT /plateforms/1.json
  def update
    respond_to do |format|
      if @plateform.update(plateform_params)
        format.html { redirect_to @plateform, notice: 'Plateform was successfully updated.' }
        format.json { render :show, status: :ok, location: @plateform }
      else
        format.html { render :edit }
        format.json { render json: @plateform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plateforms/1
  # DELETE /plateforms/1.json
  def destroy
    @plateform.destroy
    respond_to do |format|
      format.html { redirect_to plateforms_url, notice: 'Plateform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plateform
      @plateform = Plateform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plateform_params
      params.require(:plateform).permit(:label)
    end
end

app/helpers/plateforms_helper.rb
module PlateformsHelper
end

app/views/plateforms/_form.html.erb
<%= form_for(@plateform) do |f| %>
  <% if @plateform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plateform.errors.count, "error") %> prohibited this plateform from being saved:</h2>

      <ul>
      <% @plateform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plateforms/edit.html.erb
<h1>Editing Plateform</h1>

<%= render 'form' %>

<%= link_to 'Show', @plateform %> |
<%= link_to 'Back', plateforms_path %>

app/views/plateforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plateforms</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plateforms.each do |plateform| %>
      <tr>
        <td><%= plateform.label %></td>
        <td><%= link_to 'Show', plateform %></td>
        <td><%= link_to 'Edit', edit_plateform_path(plateform) %></td>
        <td><%= link_to 'Destroy', plateform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plateform', new_plateform_path %>

app/views/plateforms/new.html.erb
<h1>New Plateform</h1>

<%= render 'form' %>

<%= link_to 'Back', plateforms_path %>

app/views/plateforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @plateform.label %>
</p>

<%= link_to 'Edit', edit_plateform_path(@plateform) %> |
<%= link_to 'Back', plateforms_path %>