config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :criteres
  resources :style_interactions
  resources :plateforms
  resources :domaines
  resources :questions
  resources :auteurs
  resources :catagories

end

app/models/domaine.rb
class Domaine < ActiveRecord::Base
  has_and_belongs_to_many :criteres
end

app/controllers/domaines_controller.rb
class DomainesController < ApplicationController
  before_action :set_domaine, only: [:show, :edit, :update, :destroy]

  # GET /domaines
  # GET /domaines.json
  def index
    @domaines = Domaine.all
  end

  # GET /domaines/1
  # GET /domaines/1.json
  def show
  end

  # GET /domaines/new
  def new
    @domaine = Domaine.new
  end

  # GET /domaines/1/edit
  def edit
  end

  # POST /domaines
  # POST /domaines.json
  def create
    @domaine = Domaine.new(domaine_params)

    respond_to do |format|
      if @domaine.save
        format.html { redirect_to @domaine, notice: 'Domaine was successfully created.' }
        format.json { render :show, status: :created, location: @domaine }
      else
        format.html { render :new }
        format.json { render json: @domaine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domaines/1
  # PATCH/PUT /domaines/1.json
  def update
    respond_to do |format|
      if @domaine.update(domaine_params)
        format.html { redirect_to @domaine, notice: 'Domaine was successfully updated.' }
        format.json { render :show, status: :ok, location: @domaine }
      else
        format.html { render :edit }
        format.json { render json: @domaine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domaines/1
  # DELETE /domaines/1.json
  def destroy
    @domaine.destroy
    respond_to do |format|
      format.html { redirect_to domaines_url, notice: 'Domaine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domaine
      @domaine = Domaine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domaine_params
      params.require(:domaine).permit(:label)
    end
end

app/helpers/domaines_helper.rb
module DomainesHelper
end

app/views/domaines/_form.html.erb
<%= form_for(@domaine) do |f| %>
  <% if @domaine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domaine.errors.count, "error") %> prohibited this domaine from being saved:</h2>

      <ul>
      <% @domaine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domaines/edit.html.erb
<h1>Editing Domaine</h1>

<%= render 'form' %>

<%= link_to 'Show', @domaine %> |
<%= link_to 'Back', domaines_path %>

app/views/domaines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Domaines</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domaines.each do |domaine| %>
      <tr>
        <td><%= domaine.label %></td>
        <td><%= link_to 'Show', domaine %></td>
        <td><%= link_to 'Edit', edit_domaine_path(domaine) %></td>
        <td><%= link_to 'Destroy', domaine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domaine', new_domaine_path %>

app/views/domaines/new.html.erb
<h1>New Domaine</h1>

<%= render 'form' %>

<%= link_to 'Back', domaines_path %>

app/views/domaines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @domaine.label %>
</p>

<%= link_to 'Edit', edit_domaine_path(@domaine) %> |
<%= link_to 'Back', domaines_path %>