config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :criteres
  resources :style_interactions
  resources :plateforms
  resources :domaines
  resources :questions
  resources :auteurs
  resources :catagories

end

app/controllers/style_interactions_controller.rb
class StyleInteractionsController < ApplicationController
  before_action :set_style_interaction, only: [:show, :edit, :update, :destroy]

  # GET /style_interactions
  # GET /style_interactions.json
  def index
    @style_interactions = StyleInteraction.all
  end

  # GET /style_interactions/1
  # GET /style_interactions/1.json
  def show
  end

  # GET /style_interactions/new
  def new
    @style_interaction = StyleInteraction.new
  end

  # GET /style_interactions/1/edit
  def edit
  end

  # POST /style_interactions
  # POST /style_interactions.json
  def create
    @style_interaction = StyleInteraction.new(style_interaction_params)

    respond_to do |format|
      if @style_interaction.save
        format.html { redirect_to @style_interaction, notice: 'Style interaction was successfully created.' }
        format.json { render :show, status: :created, location: @style_interaction }
      else
        format.html { render :new }
        format.json { render json: @style_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /style_interactions/1
  # PATCH/PUT /style_interactions/1.json
  def update
    respond_to do |format|
      if @style_interaction.update(style_interaction_params)
        format.html { redirect_to @style_interaction, notice: 'Style interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @style_interaction }
      else
        format.html { render :edit }
        format.json { render json: @style_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /style_interactions/1
  # DELETE /style_interactions/1.json
  def destroy
    @style_interaction.destroy
    respond_to do |format|
      format.html { redirect_to style_interactions_url, notice: 'Style interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style_interaction
      @style_interaction = StyleInteraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_interaction_params
      params.require(:style_interaction).permit(:label)
    end
end

app/helpers/style_interactions_helper.rb
module StyleInteractionsHelper
end

app/views/style_interactions/_form.html.erb
<%= form_for(@style_interaction) do |f| %>
  <% if @style_interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style_interaction.errors.count, "error") %> prohibited this style_interaction from being saved:</h2>

      <ul>
      <% @style_interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/style_interactions/edit.html.erb
<h1>Editing Style Interaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @style_interaction %> |
<%= link_to 'Back', style_interactions_path %>

app/views/style_interactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Style Interactions</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @style_interactions.each do |style_interaction| %>
      <tr>
        <td><%= style_interaction.label %></td>
        <td><%= link_to 'Show', style_interaction %></td>
        <td><%= link_to 'Edit', edit_style_interaction_path(style_interaction) %></td>
        <td><%= link_to 'Destroy', style_interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style interaction', new_style_interaction_path %>

app/views/style_interactions/new.html.erb
<h1>New Style Interaction</h1>

<%= render 'form' %>

<%= link_to 'Back', style_interactions_path %>

app/views/style_interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @style_interaction.label %>
</p>

<%= link_to 'Edit', edit_style_interaction_path(@style_interaction) %> |
<%= link_to 'Back', style_interactions_path %>